# Names and student IDs

Paula Dewenter (i6223506) &
Ilse Heijnen (i6234910)

# **Introduction**

*(Formulate a research question that allows for explorations and comparisons. For example: How have vaccinations influenced hospitalizations in different European Union (EU) countries? You can divide this in two steps: 1. How vaccinations have influenced hospitalizations in a country (i.e Netherlands or Italy); 2. How does one country compare to the other countries in the EU? ***(5 pt)*** )*

Thailand and Malaysia are both countries in South-East Asia that have economically grown much last decades. For this report, the two countries were put side to side on economical, health care and education variables in order to find comparisons and differences.


### Research Questions
Research Question 1:
How does the allocation of healthcare expenditure and vaccination coverage differ between Thailand and Malaysia, and what impact do these differences have on health outcomes such as life expectancy and infant mortality?

Research Question 2:
To what extent does the level of education, as measured by schooling years, correlate with health outcomes such as life expectancy and infant mortality in Thailand and Malaysia, and how does this relationship compare between the two countries?




# **Data Preparation**

*Load the dataset using this link for health factors dataLinks to an external site.. Copy the link and load it as you did in the practicals. ***(5 pt)***

*Select rows and columns relevant to your research question. ***(15 pt)***

##*Loading of Dataset*
Pandas was imported into Colab. Then the dataset that was provided via the link in Canvas was loaded. The dataset was given the name df for dataframe. Later this will be renamed to a more specific name, when the relevant rows and columns are selected. By using df.head(), the columns and the first few rows of the dataframe were visualised.

In [504]:
import pandas as pd

#load the dataset using the link

url = "https://raw.githubusercontent.com/NHameleers/dtz2025-datasets/master/CountryHealthFactors.csv"
df = pd.read_csv(url)
df.head()



Country  Year      Status  Life expectancy   Adult Mortality  \
0  Afghanistan  2015  Developing              65.0            263.0   
1  Afghanistan  2014  Developing              59.9            271.0   
2  Afghanistan  2013  Developing              59.9            268.0   
3  Afghanistan  2012  Developing              59.5            272.0   
4  Afghanistan  2011  Developing              59.2            275.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   ...  \
0             62     0.01               71.279624         65.0      1154  ...   
1             64     0.01               73.523582         62.0       492  ...   
2             66     0.01               73.219243         64.0       430  ...   
3             69     0.01               78.184215         67.0      2787  ...   
4             71     0.01                7.097109         68.0      3013  ...   

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.0               8.16         65.0        0.1  584.259210  33736494.0   
1   58.0               8.18         62.0        0.1  612.696514    327582.0   
2   62.0               8.13         64.0        0.1  631.744976  31731688.0   
3   67.0               8.52         67.0        0.1  669.959000   3696958.0   
4   68.0               7.87         68.0        0.1   63.537231   2978599.0   

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3   
1                   17.5                 17.5   
2                   17.7                 17.7   
3                   17.9                 18.0   
4                   18.2                 18.2   

   Income composition of resources  Schooling  
0                            0.479       10.1  
1                            0.476       10.0  
2                            0.470        9.9  
3                            0.463        9.8  
4                            0.454        9.5  

[5 rows x 22 columns]

## *Cleaning up of column names*
Some variables had too many spaces in the column names. Furthermore some column names were capitalised, while some were not. These inconsistencies were removed in the next step. Then df.head() was used again to check the outcome.

In [505]:
df = df.rename(columns=str.strip)
df = df.rename(columns=str.lower)
df.head()


country  year      status  life expectancy  adult mortality  \
0  Afghanistan  2015  Developing             65.0            263.0   
1  Afghanistan  2014  Developing             59.9            271.0   
2  Afghanistan  2013  Developing             59.9            268.0   
3  Afghanistan  2012  Developing             59.5            272.0   
4  Afghanistan  2011  Developing             59.2            275.0   

   infant deaths  alcohol  percentage expenditure  hepatitis b  measles  ...  \
0             62     0.01               71.279624         65.0     1154  ...   
1             64     0.01               73.523582         62.0      492  ...   
2             66     0.01               73.219243         64.0      430  ...   
3             69     0.01               78.184215         67.0     2787  ...   
4             71     0.01                7.097109         68.0     3013  ...   

   polio  total expenditure  diphtheria  hiv/aids         gdp  population  \
0    6.0               8.16        65.0       0.1  584.259210  33736494.0   
1   58.0               8.18        62.0       0.1  612.696514    327582.0   
2   62.0               8.13        64.0       0.1  631.744976  31731688.0   
3   67.0               8.52        67.0       0.1  669.959000   3696958.0   
4   68.0               7.87        68.0       0.1   63.537231   2978599.0   

   thinness  1-19 years  thinness 5-9 years  income composition of resources  \
0                  17.2                17.3                            0.479   
1                  17.5                17.5                            0.476   
2                  17.7                17.7                            0.470   
3                  17.9                18.0                            0.463   
4                  18.2                18.2                            0.454   

   schooling  
0       10.1  
1       10.0  
2        9.9  
3        9.8  
4        9.5  

[5 rows x 22 columns]

## *Selection of the relevant rows and columns*
The countries Thailand and Malaysia were chosen to compare for our research quesitons. Therefor, these were called the selected countries. A new dataframe was made, called main_df, that only contained the rows of the selected countries.

Moreover, the columns that were relevant for the research questions were selected.

For research question 1, the variables 'population, 'gdp', 'percentage expenditure', 'hepatitis b', 'polio', 'diphteria', 'life expectancy', 'adult mortality', 'infant deaths' and 'under-five deaths' were explored for both countries.

For research question 2, the variables 'population', 'gdp', 'percentage expenditure', 'under-five deaths', 'infant death' and 'schooling' were explored for both countries.


To make sure the dataframe contained the right rows and columns, main_df.head(35) was used. (35) was used so that we could see all data, since both countries consisted of 16 rows, (35) would show us the full dataframe.

Furthermore, four seperate dataframes were made. One with the variables of research question 1 for Thailand, one with the variables for research question 1 for Malaysia, one for research question 2 for Thailand and one for research question 2 for Malaysia. These dataframes included the beforementioned variables, including 'year' as well.



In [506]:
# select rows and columns relevant to our research questions
selected_countries = ['Thailand', 'Malaysia']
main_df = df[df['country'].isin(selected_countries)]

columns_of_interest = ['country', 'year', 'life expectancy', 'adult mortality', 'infant deaths', 'percentage expenditure', 'hepatitis b', 'under-five deaths', 'polio', 'diphtheria', 'population', 'gdp', 'schooling']
main_df = main_df[columns_of_interest]

main_df.head(35)

country  year  life expectancy  adult mortality  infant deaths  \
1586  Malaysia  2015             75.0            123.0              4   
1587  Malaysia  2014             74.8            126.0              4   
1588  Malaysia  2013             74.6            128.0              3   
1589  Malaysia  2012             74.5            129.0              3   
1590  Malaysia  2011             74.3             13.0              3   
1591  Malaysia  2010             74.1            131.0              3   
1592  Malaysia  2009             74.0            131.0              3   
1593  Malaysia  2008             73.8            132.0              3   
1594  Malaysia  2007             73.7            133.0              3   
1595  Malaysia  2006             73.6            134.0              3   
1596  Malaysia  2005             73.4            135.0              3   
1597  Malaysia  2004             73.2            137.0              3   
1598  Malaysia  2003             73.1            138.0              3   
1599  Malaysia  2002             72.9             14.0              4   
1600  Malaysia  2001             72.7            144.0              4   
1601  Malaysia  2000             72.4            149.0              4   
2569  Thailand  2015             74.9            148.0              8   
2570  Thailand  2014             74.6            152.0              8   
2571  Thailand  2013             74.5            153.0              9   
2572  Thailand  2012             74.3            154.0              9   
2573  Thailand  2011             74.1            155.0             10   
2574  Thailand  2010             73.9            158.0             10   
2575  Thailand  2009             73.7             16.0             11   
2576  Thailand  2008             73.5            162.0             11   
2577  Thailand  2007             73.3            165.0             12   
2578  Thailand  2006             73.0            168.0             13   
2579  Thailand  2005             72.5            177.0             13   
2580  Thailand  2004             71.6            189.0             14   
2581  Thailand  2003             71.7            189.0             15   
2582  Thailand  2002             71.4            192.0             16   
2583  Thailand  2001             71.2            194.0             17   
2584  Thailand  2000             71.1            194.0             18   

      percentage expenditure  hepatitis b  under-five deaths  polio  \
1586                0.000000         99.0                  4   99.0   
1587              721.365543         96.0                  4   97.0   
1588              110.677971         96.0                  4   97.0   
1589              101.609245         97.0                  4   97.0   
1590                9.230026         96.0                  4   96.0   
1591               65.566597         96.0                  4   96.0   
1592              431.545247         96.0                  4   97.0   
1593              438.451921         97.0                  4   97.0   
1594              409.981252         96.0                  4   97.0   
1595              365.911398         95.0                  4   95.0   
1596              297.591383         96.0                  4   96.0   
1597              315.663932         94.0                  4   95.0   
1598              264.249613         95.0                  4   96.0   
1599              216.702948         95.0                  4   94.0   
1600              210.241700         95.0                  5   95.0   
1601               23.371672         97.0                  5   98.0   
2569                0.000000         99.0                  9   99.0   
2570              789.077295         99.0                 10   99.0   
2571              788.687340         99.0                 10   99.0   
2572              801.050465         98.0                 11   99.0   
2573              748.445105         98.0                 11   99.0   
2574               71.685091       

In [507]:
#make dfs for RQ1
columns_of_interestrq1 = ['country', 'year','population', 'gdp', 'percentage expenditure', 'hepatitis b', 'polio', 'diphtheria', 'life expectancy', 'adult mortality', 'infant deaths', 'under-five deaths']
rq1_df = main_df[columns_of_interestrq1]
rq1_df.head()

country  year  population           gdp  percentage expenditure  \
1586  Malaysia  2015   3723155.0   9643.644683                0.000000   
1587  Malaysia  2014    322817.0  11183.961910              721.365543   
1588  Malaysia  2013   2976724.0   1882.278420              110.677971   
1589  Malaysia  2012   2917456.0   1779.496410              101.609245   
1590  Malaysia  2011  28635128.0    145.126200                9.230026   

      hepatitis b  polio  diphtheria  life expectancy  adult mortality  \
1586         99.0   99.0        99.0             75.0            123.0   
1587         96.0   97.0        97.0             74.8            126.0   
1588         96.0   97.0        97.0             74.6            128.0   
1589         97.0   97.0        97.0             74.5            129.0   
1590         96.0   96.0        96.0             74.3             13.0   

      infant deaths  under-five deaths  
1586              4                  4  
1587              4                  4  
1588              3                  4  
1589              3                  4  
1590              3                  4

In [508]:
rq1_thailand = ['Thailand']
rq1_thailand_df = rq1_df[rq1_df['country'].isin(rq1_thailand)]
rq1_thailand_df.head()


country  year  population          gdp  percentage expenditure  \
2569  Thailand  2015    686576.0  5814.863134                0.000000   
2570  Thailand  2014  68416772.0  5941.847100              789.077295   
2571  Thailand  2013   6814365.0  6171.262444              788.687340   
2572  Thailand  2012  67843979.0  5859.915622              801.050465   
2573  Thailand  2011    675313.0  5491.159981              748.445105   

      hepatitis b  polio  diphtheria  life expectancy  adult mortality  \
2569         99.0   99.0        99.0             74.9            148.0   
2570         99.0   99.0        99.0             74.6            152.0   
2571         99.0   99.0        99.0             74.5            153.0   
2572         98.0   99.0        99.0             74.3            154.0   
2573         98.0   99.0        99.0             74.1            155.0   

      infant deaths  under-five deaths  
2569              8                  9  
2570              8                 10  
2571              9                 10  
2572              9                 11  
2573             10                 11

In [509]:
rq1_malaysia = ['Malaysia']
rq1_malaysia_df = rq1_df[rq1_df['country'].isin(rq1_malaysia)]
rq1_malaysia_df.head()

country  year  population           gdp  percentage expenditure  \
1586  Malaysia  2015   3723155.0   9643.644683                0.000000   
1587  Malaysia  2014    322817.0  11183.961910              721.365543   
1588  Malaysia  2013   2976724.0   1882.278420              110.677971   
1589  Malaysia  2012   2917456.0   1779.496410              101.609245   
1590  Malaysia  2011  28635128.0    145.126200                9.230026   

      hepatitis b  polio  diphtheria  life expectancy  adult mortality  \
1586         99.0   99.0        99.0             75.0            123.0   
1587         96.0   97.0        97.0             74.8            126.0   
1588         96.0   97.0        97.0             74.6            128.0   
1589         97.0   97.0        97.0             74.5            129.0   
1590         96.0   96.0        96.0             74.3             13.0   

      infant deaths  under-five deaths  
1586              4                  4  
1587              4                  4  
1588              3                  4  
1589              3                  4  
1590              3                  4

In [510]:
#make dfs for RQ2
columns_of_interestrq2 = ['country', 'year', 'population', 'gdp', 'percentage expenditure', 'under-five deaths', 'infant deaths', 'schooling']
rq2_df = main_df[columns_of_interestrq2]
rq2_df.head()

country  year  population           gdp  percentage expenditure  \
1586  Malaysia  2015   3723155.0   9643.644683                0.000000   
1587  Malaysia  2014    322817.0  11183.961910              721.365543   
1588  Malaysia  2013   2976724.0   1882.278420              110.677971   
1589  Malaysia  2012   2917456.0   1779.496410              101.609245   
1590  Malaysia  2011  28635128.0    145.126200                9.230026   

      under-five deaths  infant deaths  schooling  
1586                  4              4       13.1  
1587                  4              4       13.0  
1588                  4              3       12.9  
1589                  4              3       12.9  
1590                  4              3       13.0

In [511]:
rq2_thailand = ['Thailand']
rq2_thailand_df = rq2_df[rq2_df['country'].isin(rq2_thailand)]
rq2_thailand_df.head()


country  year  population          gdp  percentage expenditure  \
2569  Thailand  2015    686576.0  5814.863134                0.000000   
2570  Thailand  2014  68416772.0  5941.847100              789.077295   
2571  Thailand  2013   6814365.0  6171.262444              788.687340   
2572  Thailand  2012  67843979.0  5859.915622              801.050465   
2573  Thailand  2011    675313.0  5491.159981              748.445105   

      under-five deaths  infant deaths  schooling  
2569                  9              8       13.6  
2570                 10              8       13.6  
2571                 10              9       13.6  
2572                 11              9       13.7  
2573                 11             10       13.3

In [512]:
rq2_malaysia = ['Malaysia']
rq2_malaysia_df = rq2_df[rq2_df['country'].isin(rq2_malaysia)]
rq2_malaysia_df.head()

country  year  population           gdp  percentage expenditure  \
1586  Malaysia  2015   3723155.0   9643.644683                0.000000   
1587  Malaysia  2014    322817.0  11183.961910              721.365543   
1588  Malaysia  2013   2976724.0   1882.278420              110.677971   
1589  Malaysia  2012   2917456.0   1779.496410              101.609245   
1590  Malaysia  2011  28635128.0    145.126200                9.230026   

      under-five deaths  infant deaths  schooling  
1586                  4              4       13.1  
1587                  4              4       13.0  
1588                  4              3       12.9  
1589                  4              3       12.9  
1590                  4              3       13.0

# **Data Exploration & Cleaning**

Exploring data using descriptive statistics or visualisations to get to know the dataset and spot possible issues (such as outliers or typos)***(10 pt)***
Identify and report issues with missing data. ***(5 pt)***
Resolve issues with missing data and clean other data inconsistencies. Report also if you found no issues and how you verified this. ***(5 pt)***

## *Data exploration using descriptive statistics and visualisations*
The datasets were explored to get a better understanding of the characteristics and to spot missing data, outliers or other inconsistencies.



### Research Question 1 - Thailand
Firstly, the dataframe for research question 1 for Thailand was explored.
Herefor, describe (), info() were used to find out the different means and counts of the dataframe. isnull() was used to find out if there are missing values.
Next, the variables were plotted to check for outliers, typos and other inconsistencies. These results were discussed in the next section, and in case there was missing data, it was identified, reported and resolved.

In [513]:
rq1_thailand_df.describe()

year    population          gdp  percentage expenditure  \
count    16.000000  1.600000e+01    16.000000               16.000000   
mean   2007.500000  3.117051e+07  3494.781702              401.259963   
std       4.760952  3.198737e+07  2087.128227              295.771637   
min    2000.000000  6.522310e+05    27.564826                0.000000   
25%    2003.750000  4.893510e+06  2242.488562              149.968163   
50%    2007.500000  6.734470e+06  3670.608663              377.558196   
75%    2011.250000  6.591703e+07  5572.085769              644.574649   
max    2015.000000  6.841677e+07  6171.262444              801.050465   

       hepatitis b    polio  diphtheria  life expectancy  adult mortality  \
count    16.000000  16.0000   16.000000        16.000000        16.000000   
mean     97.000000  98.3125   98.187500        73.081250       160.375000   
std       1.505545   0.7932    1.046821         1.320716        41.996627   
min      95.000000  97.0000   96.000000        71.100000        16.000000   
25%      96.000000  98.0000   98.000000        71.675000       153.750000   
50%      97.000000  98.5000   98.500000        73.400000       163.500000   
75%      98.000000  99.0000   99.000000        74.150000       189.000000   
max      99.000000  99.0000   99.000000        74.900000       194.000000   

       infant deaths  under-five deaths  
count      16.000000          16.000000  
mean       12.125000          14.125000  
std         3.180671           3.792537  
min         8.000000           9.000000  
25%         9.750000          11.000000  
50%        11.500000          13.500000  
75%        14.250000          16.500000  
max        18.000000          21.000000

The standard deviations for population, GDP, percentage expenditure and adult mortality are rather large. This could indicate outliers or other issues with the data, like missing data.

The vaccination rates are quite high. This is something we did not expect.  

In [514]:
rq1_thailand_df.isnull().sum()

country                   0
year                      0
population                0
gdp                       0
percentage expenditure    0
hepatitis b               0
polio                     0
diphtheria                0
life expectancy           0
adult mortality           0
infant deaths             0
under-five deaths         0
dtype: int64

There are no missing values in this dataframe.

In order to explore the data and to check for inconsistencies and outliers, scatterplots were made of the variables.

#### *RQ 1 - Thailand: Population Of The Country Over Time*

In [515]:
import altair as alt

alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Thailand) '
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#1)
In the graph above there are outliers for the years 2000, 2002, 2004, 2005, 2008, 2010, 2011, 2013 and 2015. A table was made to visualise these values.

In [516]:
tablepopulation_thailandrq1 = rq1_thailand_df.groupby('year')['population'].sum().reset_index()
print(tablepopulation_thailandrq1)

    year  population
0   2000   6295821.0
1   2001  63543322.0
2   2002   6473164.0
3   2003  64554952.0
4   2004    652231.0
5   2005   6542547.0
6   2006  65824164.0
7   2007  66195615.0
8   2008   6654576.0
9   2009  66881867.0
10  2010    672888.0
11  2011    675313.0
12  2012  67843979.0
13  2013   6814365.0
14  2014  68416772.0
15  2015    686576.0


In this table, it became clear that the most probable issues with the values were missplaced decimals.

In [517]:
#seperate population df was made with only population
rq1_thailand_pop_df = rq1_thailand_df[['population']].copy()

#the misplaced decimals were corrected
rq1_thailand_pop_df['population'] = rq1_thailand_pop_df['population'].astype(str) #converted to string so it can be manipulated
rq1_thailand_pop_df['population'] = rq1_thailand_pop_df['population'].str.replace('.', '') #non-numeric characters were removed
rq1_thailand_pop_df['population'] = rq1_thailand_pop_df['population'].apply(lambda x: x[:-1] + '.' + x[-1] if len(x) > 6 else x) #decimal places were adjusted if needed
rq1_thailand_pop_df['population'] = rq1_thailand_pop_df['population'].astype(float) #converted back to float

#checked if corrected correclty by making a table
print(rq1_thailand_pop_df.head(16))


      population
2569    686576.0
2570  68416772.0
2571   6814365.0
2572  67843979.0
2573    675313.0
2574    672888.0
2575  66881867.0
2576   6654576.0
2577  66195615.0
2578  65824164.0
2579   6542547.0
2580    652231.0
2581  64554952.0
2582   6473164.0
2583  63543322.0
2584   6295821.0


<ipython-input-517-25c3acc2629a>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  rq1_thailand_pop_df['population'] = rq1_thailand_pop_df['population'].str.replace('.', '') #non-numeric characters were removed


That approach did not work for some reason. Next, another approach was tried. The population of Thailand was checked online, and was verified that the population of Thailand was around 62 million in 2000. Setting this as a treshold, the outliers can be filtered. Then for these outliers, the decimal can be moved to the right.

In [518]:
population_threshold = 62000000

while rq1_thailand_pop_df['population'].min() < population_threshold:

   outliers_population = rq1_thailand_pop_df['population'] < population_threshold

   rq1_thailand_pop_df.loc[outliers_population, 'population'] *= 10

print(rq1_thailand_pop_df)

      population
2569  68657600.0
2570  68416772.0
2571  68143650.0
2572  67843979.0
2573  67531300.0
2574  67288800.0
2575  66881867.0
2576  66545760.0
2577  66195615.0
2578  65824164.0
2579  65425470.0
2580  65223100.0
2581  64554952.0
2582  64731640.0
2583  63543322.0
2584  62958210.0


This approach worked. The corrected population values were put back in the 'rq1_thailand_df' to replace the values with the outliers.
To check if it worked correctly, the population was plotted over time.

In [519]:
rq1_thailand_df['population'] = rq1_thailand_pop_df['population']


<ipython-input-519-92917e1e9357>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_thailand_df['population'] = rq1_thailand_pop_df['population']


In [520]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Thailand) '
).interactive()

alt.Chart(...)

Inconsistencies were resolved!

#### *Gross Domestic Product per capita (in USD) Over Time*

In [521]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title="GDP Over Time - Thailand"
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#2)

Here, there are outliers at the year 2000, 2002, and 2010. To visualise the values, a table was made.

In [522]:
tablegdp_thailandrq1 = rq1_thailand_df.groupby('year')['gdp'].sum().reset_index()
print(tablegdp_thailandrq1)

    year          gdp
0   2000    27.564826
1   2001  1893.145377
2   2002   296.546170
3   2003  2358.936290
4   2004  2659.839180
5   2005  2893.651356
6   2006  3368.952576
7   2007  3972.264750
8   2008  4378.687460
9   2009  4212.549200
10  2010   575.321760
11  2011  5491.159981
12  2012  5859.915622
13  2013  6171.262444
14  2014  5941.847100
15  2015  5814.863134


Here, there does not seem to be a missplaced decimal like for the previous case. Therefor, the best approach seems to remove the outliers from of the dataset. A seperate dataframe was made. As threshold, the value for 2001 (1893) was taken. All values under the treshold were deleted. The corrected dataframe was merged back into the RQ 1 - Thailand dataframe. To check if this resolved the inconsistency correctly , GDP over Time was plotted again.  

In [523]:
#seperate gdp df was made with only population
rq1_thailand_gdp_df = rq1_thailand_df[['gdp']].copy()

In [524]:
#threshold was set at 1893
gdp_threshold = 1893

#loop to identify outliers

while rq1_thailand_gdp_df['gdp'].min() < gdp_threshold:

   outliers_gdp = rq1_thailand_gdp_df['gdp'] < gdp_threshold

#drop rows corresponding to outliers
   rq1_thailand_gdp_df = rq1_thailand_gdp_df[~outliers_gdp]

print(rq1_thailand_gdp_df)

              gdp
2569  5814.863134
2570  5941.847100
2571  6171.262444
2572  5859.915622
2573  5491.159981
2575  4212.549200
2576  4378.687460
2577  3972.264750
2578  3368.952576
2579  2893.651356
2580  2659.839180
2581  2358.936290
2583  1893.145377


In [525]:
rq1_thailand_df['gdp'] = rq1_thailand_gdp_df['gdp']

<ipython-input-525-138ee0d85820>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_thailand_df['gdp'] = rq1_thailand_gdp_df['gdp']


In [526]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Thailand) '
).interactive()

alt.Chart(...)

This did not do what it we intended to do. A new approach was tried to fill in the outliers with interpolation.

In [527]:
tablegdp_thailandrq1 = rq1_thailand_df.groupby('year')['gdp'].sum().reset_index()
print(tablegdp_thailandrq1)

    year          gdp
0   2000     0.000000
1   2001  1893.145377
2   2002     0.000000
3   2003  2358.936290
4   2004  2659.839180
5   2005  2893.651356
6   2006  3368.952576
7   2007  3972.264750
8   2008  4378.687460
9   2009  4212.549200
10  2010     0.000000
11  2011  5491.159981
12  2012  5859.915622
13  2013  6171.262444
14  2014  5941.847100
15  2015  5814.863134


In [528]:
rq1_thailand_gdp2_df = rq1_thailand_df[['gdp']].copy()

In [529]:
import numpy as np

#the 0s were replaced with nans
rq1_thailand_gdp2_df.replace(0, np.nan, inplace=True)

#missing values in the df were interpolated
rq1_thailand_gdp2_df['gdp'] = rq1_thailand_gdp2_df['gdp'].interpolate(method='linear')


print(rq1_thailand_gdp2_df)

              gdp
2569  5814.863134
2570  5941.847100
2571  6171.262444
2572  5859.915622
2573  5491.159981
2574  4851.854591
2575  4212.549200
2576  4378.687460
2577  3972.264750
2578  3368.952576
2579  2893.651356
2580  2659.839180
2581  2358.936290
2582  2126.040834
2583  1893.145377
2584  1893.145377


In [530]:
rq1_thailand_df['gdp'] = rq1_thailand_gdp2_df['gdp']

<ipython-input-530-ce9255ac984b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_thailand_df['gdp'] = rq1_thailand_gdp2_df['gdp']


In [531]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Thailand) '
).interactive()

alt.Chart(...)

The inconsistencies were resolved!

#### *Expenditure on health as a percentage of Gross Domestic Product per capita(%) Over Time*

In [532]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage expenditure on health care Over Time - Thailand'
).interactive()


alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#**3**)

The data seems to not make sense. The percentage expenditure is supposed to be a percentage of the GDP per capita spent on health care. However here, the values are mostly above 100%. A table was made to visualise.

In [533]:
tableexp_thailandrq1 = rq1_thailand_df.groupby('year')['percentage expenditure'].sum().reset_index()
print(tableexp_thailandrq1)

    year  percentage expenditure
0   2000                0.275648
1   2001              176.062520
2   2002               27.638103
3   2003              282.836461
4   2004              301.359779
5   2005              321.195300
6   2006              433.921092
7   2007              520.763909
8   2008              609.951163
9   2009              547.210141
10  2010               71.685091
11  2011              748.445105
12  2012              801.050465
13  2013              788.687340
14  2014              789.077295
15  2015                0.000000


All values, except for 2002, and 2010 do not make sense. It could be that here again, the decimal is placed on wrong. A threshold was made at 100 (%). Then, the same approach as for population was used to replace the decimal correctly.

In [534]:
#seperate exp df was made with only expenditure percentage
rq1_thailand_exp_df = rq1_thailand_df[['percentage expenditure']].copy()

In [535]:
exp_threshold = 100

while rq1_thailand_exp_df['percentage expenditure'].max() > exp_threshold:

   outliers_exp = rq1_thailand_exp_df['percentage expenditure'] > exp_threshold

   rq1_thailand_exp_df.loc[outliers_exp, 'percentage expenditure'] /= 10

print(rq1_thailand_exp_df)

      percentage expenditure
2569                0.000000
2570               78.907729
2571               78.868734
2572               80.105047
2573               74.844511
2574               71.685091
2575               54.721014
2576               60.995116
2577               52.076391
2578               43.392109
2579               32.119530
2580               30.135978
2581               28.283646
2582               27.638103
2583               17.606252
2584                0.275648


Only the first and the last value are now still off. A linear regression method was tried to extrapolate the values in order to get more correct values for the first and last value.

In [536]:
from sklearn.linear_model import LinearRegression

#year values extracted
years = rq1_thailand_exp_df.index.values.reshape(-1, 1)

#percentage expenditure values extracted
expenditure = rq1_thailand_exp_df['percentage expenditure'].values.reshape(-1, 1)

#linear regression model fitted
model = LinearRegression()
model.fit(years, expenditure)

#the first and last values extrapolated using the linear model
first_value = model.predict([[years[0][0] - 1]])[0][0]
last_value = model.predict([[years[-1][0] + 1]])[0][0]

#the first and last values updated in the df
rq1_thailand_exp_df.iloc[0, 0] = first_value
rq1_thailand_exp_df.iloc[-1, 0] = last_value

print(rq1_thailand_exp_df)


      percentage expenditure
2569               75.433519
2570               78.907729
2571               78.868734
2572               80.105047
2573               74.844511
2574               71.685091
2575               54.721014
2576               60.995116
2577               52.076391
2578               43.392109
2579               32.119530
2580               30.135978
2581               28.283646
2582               27.638103
2583               17.606252
2584               16.023344


In [537]:
rq1_thailand_df['percentage expenditure'] = rq1_thailand_exp_df['percentage expenditure']

<ipython-input-537-d8775f7cc0c5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_thailand_df['percentage expenditure'] = rq1_thailand_exp_df['percentage expenditure']


In [538]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage expenditure Over Time (Thailand) '
).interactive()

alt.Chart(...)

Inconsistencies were solved!

#### *Hepatitis B (HepB) immunization coverage among 1-year-olds (%) Over Time*

In [539]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='hepatitis b:Q',
    tooltip=['year', 'hepatitis b']
).properties(
    width=600,
    height=400,
    title='Hepatitis B Vaccination Coverage Over Time - Thailand'
).interactive()


alt.Chart(...)

#### *Polio (Pol3) immunization coverage among 1-year-olds (%) Over Time*

In [540]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='polio:Q',
    tooltip=['year', 'polio']
).properties(
    width=600,
    height=400,
    title='Polio Vaccination Coverage Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%) Over Time*

In [541]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='diphtheria:Q',
    tooltip=['year', 'diphtheria']
).properties(
    width=600,
    height=400,
    title='Diphtheria Vaccination Coverage Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Life Expectancy Over Time*

In [542]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='life expectancy:Q',
    tooltip=['year', 'life expectancy']
).properties(
    width=600,
    height=400,
    title= 'Life expectancy Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population) Over Time*

In [543]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='adult mortality:Q',
    tooltip=['year', 'adult mortality']
).properties(
    width=600,
    height=400,
    title='Adult Mortality Over Time - Thailand'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#4)

Here, there is one clear outlier, at 2009. To visualise, a table was made.

In [544]:
tableadultmort_thailandrq1 = rq1_thailand_df.groupby('year')['adult mortality'].sum().reset_index()
print(tableadultmort_thailandrq1)

    year  adult mortality
0   2000            194.0
1   2001            194.0
2   2002            192.0
3   2003            189.0
4   2004            189.0
5   2005            177.0
6   2006            168.0
7   2007            165.0
8   2008            162.0
9   2009             16.0
10  2010            158.0
11  2011            155.0
12  2012            154.0
13  2013            153.0
14  2014            152.0
15  2015            148.0


It is clear that it is highly probable again a missplaced decimal. A similar loop as for the population inconsistencies was applied, with 100 as a threshold.

In [545]:
rq1_thailand_adultmort_df = rq1_thailand_df[['adult mortality']].copy()
adultmort_threshold = 100

while rq1_thailand_adultmort_df['adult mortality'].min() < adultmort_threshold:

   outliers_adultmort = rq1_thailand_adultmort_df['adult mortality'] < adultmort_threshold

   rq1_thailand_adultmort_df.loc[outliers_adultmort, 'adult mortality'] *= 10

print(rq1_thailand_adultmort_df)

      adult mortality
2569            148.0
2570            152.0
2571            153.0
2572            154.0
2573            155.0
2574            158.0
2575            160.0
2576            162.0
2577            165.0
2578            168.0
2579            177.0
2580            189.0
2581            189.0
2582            192.0
2583            194.0
2584            194.0


In [546]:
rq1_thailand_df['adult mortality'] = rq1_thailand_adultmort_df['adult mortality']

<ipython-input-546-6e92ca0ab61c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_thailand_df['adult mortality'] = rq1_thailand_adultmort_df['adult mortality']


In [547]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='adult mortality:Q',
    tooltip=['year', 'adult mortality']
).properties(
    width=600,
    height=400,
    title='Adult Mortality Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Number of Infant Deaths per 1000 population Over Time*

In [548]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='infant deaths:Q',
    tooltip=['country', 'year', 'infant deaths']
).properties(
    width=600,
    height=400,
    title='Infant Deaths Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Number of under-five deaths per 1000 population Over Time*

In [549]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='under-five deaths:Q',
    tooltip=['year', 'under-five deaths']
).properties(
    width=600,
    height=400,
    title='Deaths under the age of 5 Over Time - Thailand'
).interactive()

alt.Chart(...)

### Research Question 1 - Malaysia

Secondly, the dataframe for research question 1 for Malaysia was explored.
Herefor, describe (), info() were used to find out the different means and counts of the dataframe. isnull() was used to find out if there are missing values.
Next, the variables were plotted to check for outliers, typos and other inconsistencies. These results were discussed in the next section, and in case there was missing data, it was identified, reported and resolved.

In [550]:
rq1_malaysia_df.describe()

year    population           gdp  percentage expenditure  \
count    16.000000  1.600000e+01     16.000000               16.000000   
mean   2007.500000  1.152916e+07   4904.938992              248.885028   
std       4.760952  1.208221e+07   3338.811459              197.722652   
min    2000.000000  3.228170e+05    145.126200                0.000000   
25%    2003.750000  2.505282e+06   1856.582918               92.598583   
50%    2007.500000  2.947090e+06   4709.576818              240.476280   
75%    2011.250000  2.578044e+07   7283.564464              376.928861   
max    2015.000000  2.863513e+07  11183.961910              721.365543   

       hepatitis b      polio  diphtheria  life expectancy  adult mortality  \
count    16.000000  16.000000   16.000000        16.000000        16.000000   
mean     96.000000  96.375000   96.437500        73.756250       118.562500   
std       1.154701   1.258306    1.209339         0.772846        41.511394   
min      94.000000  94.000000   94.000000        72.400000        13.000000   
25%      95.000000  95.750000   96.000000        73.175000       127.500000   
50%      96.000000  96.500000   96.500000        73.750000       131.500000   
75%      96.250000  97.000000   97.000000        74.350000       135.500000   
max      99.000000  99.000000   99.000000        75.000000       149.000000   

       infant deaths  under-five deaths  
count      16.000000          16.000000  
mean        3.312500           4.125000  
std         0.478714           0.341565  
min         3.000000           4.000000  
25%         3.000000           4.000000  
50%         3.000000           4.000000  
75%         4.000000           4.000000  
max         4.000000           5.000000

In [551]:
rq1_malaysia_df.isnull().sum()

country                   0
year                      0
population                0
gdp                       0
percentage expenditure    0
hepatitis b               0
polio                     0
diphtheria                0
life expectancy           0
adult mortality           0
infant deaths             0
under-five deaths         0
dtype: int64

#### *RQ 1 - Malaysia: Population Of The Country Over Time*

In [552]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Malaysia) '
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#5)

In the graph above there are outliers for the years 2000, 2001, 2003, 2004, 2008, 2009, 2012, 2013, 2014, 2015. A table was made to visualise these values.

In [553]:
tablepopulation_malaysiarq1 = rq1_malaysia_df.groupby('year')['population'].sum().reset_index()
print(tablepopulation_malaysiarq1)

    year  population
0   2000   2318568.0
1   2001   2369897.0
2   2002  24198811.0
3   2003   2468873.0
4   2004   2517419.0
5   2005  25659393.0
6   2006  26143566.0
7   2007  26625845.0
8   2008   2711169.0
9   2009   2765383.0
10  2010  28112289.0
11  2011  28635128.0
12  2012   2917456.0
13  2013   2976724.0
14  2014    322817.0
15  2015   3723155.0


Like the population outliers in RQ 1 Thailand, the problem seems to be a missplaced decimal. The same approach was applied.
The population of Malaysia was checked online, and was verified that the population of Malaysia was around 22 million in 2000. Setting this as a treshold, the outliers can be filtered. Then for these outliers, the decimal can be moved to the right.

In [554]:
rq1_malaysia_pop_df = rq1_malaysia_df[['population']].copy()
population_threshold = 22000000

while rq1_malaysia_pop_df['population'].min() < population_threshold:

   outliers_population = rq1_malaysia_pop_df['population'] < population_threshold

   rq1_malaysia_pop_df.loc[outliers_population, 'population'] *= 10

print(rq1_malaysia_pop_df)

      population
1586  37231550.0
1587  32281700.0
1588  29767240.0
1589  29174560.0
1590  28635128.0
1591  28112289.0
1592  27653830.0
1593  27111690.0
1594  26625845.0
1595  26143566.0
1596  25659393.0
1597  25174190.0
1598  24688730.0
1599  24198811.0
1600  23698970.0
1601  23185680.0


This approach worked. The corrected population values were put back in the 'rq1_malaysia_df' to replace the values with the outliers. To check if it worked correctly, the population was plotted over time.

In [555]:
rq1_malaysia_df['population'] = rq1_malaysia_pop_df['population']

<ipython-input-555-ae759afad161>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_malaysia_df['population'] = rq1_malaysia_pop_df['population']


In [556]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Malaysia) '
).interactive()

alt.Chart(...)

The inconsistencies were resolved!

#### *Gross Domestic Product per capita (in USD) Over Time*

In [557]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#6)

Here, there are outliers at 2000, 2010, 2011 and 2012. To visualise the value, a table was made.

In [558]:
tablegdp_malaysiarq1 = rq1_malaysia_df.groupby('year')['gdp'].sum().reset_index()
print(tablegdp_malaysiarq1)

    year           gdp
0   2000    445.174710
1   2001   3915.115460
2   2002   4167.364387
3   2003   4463.675893
4   2004   4955.477743
5   2005   5593.822995
6   2006   6222.982955
7   2007   7269.171140
8   2008   8513.629541
9   2009   7326.744435
10  2010    971.356987
11  2011    145.126200
12  2012   1779.496410
13  2013   1882.278420
14  2014  11183.961910
15  2015   9643.644683


Probably this could be misplaced decimals again. The same approach was applied. The GDP per capita in Malaysia in according to the world bank was 4087 USD. However, the GDP in our data in 2001 is 3915, thus that was set as the threshold.

In [559]:
rq1_malaysia_gdp_df = rq1_malaysia_df[['gdp']].copy()

In [560]:
#threshold
gdp_threshold = 3915

#loop
while rq1_malaysia_gdp_df['gdp'].min() < gdp_threshold:

   outliers_gdp = rq1_malaysia_gdp_df['gdp'] < gdp_threshold

   rq1_malaysia_gdp_df.loc[outliers_gdp, 'gdp'] *= 10

print(rq1_malaysia_gdp_df)


               gdp
1586   9643.644683
1587  11183.961910
1588  18822.784200
1589  17794.964100
1590  14512.620000
1591   9713.569870
1592   7326.744435
1593   8513.629541
1594   7269.171140
1595   6222.982955
1596   5593.822995
1597   4955.477743
1598   4463.675893
1599   4167.364387
1600   3915.115460
1601   4451.747100


In [561]:
rq1_malaysia_df['gdp'] = rq1_malaysia_gdp_df['gdp']

<ipython-input-561-4285c6ab157f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_malaysia_df['gdp'] = rq1_malaysia_gdp_df['gdp']


In [562]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Malaysia) '
).interactive()

alt.Chart(...)

Inconsistencies were resolved!

#### *Expenditure on health as a percentage of Gross Domestic Product per capita(%) Over Time*

In [563]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage Expenditure Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#7)

Here, there are outliers in the year 2000, 2010, 2011, 2012, 2013 and 2015. To visualise, a table was made.

In [564]:
tableexp_malaysiarq1 = rq1_malaysia_df.groupby('year')['percentage expenditure'].sum().reset_index()
print(tableexp_malaysiarq1)

    year  percentage expenditure
0   2000               23.371672
1   2001              210.241700
2   2002              216.702948
3   2003              264.249613
4   2004              315.663932
5   2005              297.591383
6   2006              365.911398
7   2007              409.981252
8   2008              438.451921
9   2009              431.545247
10  2010               65.566597
11  2011                9.230026
12  2012              101.609245
13  2013              110.677971
14  2014              721.365543
15  2015                0.000000


Here, the problem seems to be the same as with R1 - Thailand Percentage Expenditure. The same approach was applied. However, some are just a bit above 100. These probably have not a misplaced decimal. Therefor, the threshold was set at 112.

In [565]:
#seperate exp df was made with only expenditure percentage
rq1_malaysia_exp_df = rq1_malaysia_df[['percentage expenditure']].copy()

In [566]:
exp_threshold = 112

while rq1_malaysia_exp_df['percentage expenditure'].max() > exp_threshold:

   outliers_exp = rq1_malaysia_exp_df['percentage expenditure'] > exp_threshold

   rq1_malaysia_exp_df.loc[outliers_exp, 'percentage expenditure'] /= 10

print(rq1_malaysia_exp_df)

      percentage expenditure
1586                0.000000
1587               72.136554
1588              110.677971
1589              101.609245
1590                9.230026
1591               65.566597
1592               43.154525
1593               43.845192
1594               40.998125
1595               36.591140
1596               29.759138
1597               31.566393
1598               26.424961
1599               21.670295
1600               21.024170
1601               23.371672


Linear regression was used again to extrapolate.

In [567]:
from sklearn.linear_model import LinearRegression

#the year values extracted
years = rq1_malaysia_exp_df.index.values.reshape(-1, 1)

#the percentage expenditure values extracted
expenditure = rq1_malaysia_exp_df['percentage expenditure'].values.reshape(-1, 1)

#the linear regression model fitted
model = LinearRegression()
model.fit(years[1:], expenditure[1:])

# the first value using the linear model extrapolated
first_value = model.predict([[years[0][0] - 1]])[0][0]

# first value in the df updated
rq1_malaysia_exp_df.iloc[0, 0] = first_value

print(rq1_malaysia_exp_df)


      percentage expenditure
1586               88.446984
1587               72.136554
1588              110.677971
1589              101.609245
1590                9.230026
1591               65.566597
1592               43.154525
1593               43.845192
1594               40.998125
1595               36.591140
1596               29.759138
1597               31.566393
1598               26.424961
1599               21.670295
1600               21.024170
1601               23.371672


In [568]:
rq1_malaysia_df['percentage expenditure'] = rq1_malaysia_exp_df['percentage expenditure']

<ipython-input-568-44dd279faa7e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_malaysia_df['percentage expenditure'] = rq1_malaysia_exp_df['percentage expenditure']


In [569]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage expenditure Over Time (Malaysia) '
).interactive()

alt.Chart(...)

Inconsistencies were (almost) resolved!

#### *Hepatitis B (HepB) immunization coverage among 1-year-olds (%) Over Time*

In [570]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='hepatitis b:Q',
    tooltip=['year', 'hepatitis b']
).properties(
    width=600,
    height=400,
    title='Hepatitis B Vaccination Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Polio (Pol3) immunization coverage among 1-year-olds (%) Over Time*

In [571]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='polio:Q',
    tooltip=['year', 'polio']
).properties(
    width=600,
    height=400,
    title='Polio Vaccination Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%) Over Time*

In [572]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='diphtheria:Q',
    tooltip=['year', 'diphtheria']
).properties(
    width=600,
    height=400,
    title='Diphtheria Vaccination Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Life Expectancy Over Time*

In [573]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='life expectancy:Q',
    tooltip=['year', 'life expectancy']
).properties(
    width=600,
    height=400,
    title='Life Expectancy Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population) Over Time*

In [574]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='adult mortality:Q',
    tooltip=['year', 'adult mortality']
).properties(
    width=600,
    height=400,
    title='Adult Mortality Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#8)

Here, there are two outliers, at 2002 and 2011. A table was made to visualise the values.

In [575]:
tableadultmort_malaysiarq1 = rq1_malaysia_df.groupby('year')['adult mortality'].sum().reset_index()
print(tableadultmort_malaysiarq1)

    year  adult mortality
0   2000            149.0
1   2001            144.0
2   2002             14.0
3   2003            138.0
4   2004            137.0
5   2005            135.0
6   2006            134.0
7   2007            133.0
8   2008            132.0
9   2009            131.0
10  2010            131.0
11  2011             13.0
12  2012            129.0
13  2013            128.0
14  2014            126.0
15  2015            123.0


Here, there seems to be the same problem again as with the adult mortality dataframe in Thailand. At the outliers, the decimals are missplaced.
Thus, also here a threshold was made, at 100. The values below 100 were mulitplied by 10 to correct the decimal placement.

In [576]:
rq1_malaysia_adultmort_df = rq1_malaysia_df[['adult mortality']].copy()
adultmort_threshold = 100

while rq1_malaysia_adultmort_df['adult mortality'].min() < adultmort_threshold:

   outliers_adultmort = rq1_malaysia_adultmort_df['adult mortality'] < adultmort_threshold

   rq1_malaysia_adultmort_df.loc[outliers_adultmort, 'adult mortality'] *= 10

print(rq1_malaysia_adultmort_df)

      adult mortality
1586            123.0
1587            126.0
1588            128.0
1589            129.0
1590            130.0
1591            131.0
1592            131.0
1593            132.0
1594            133.0
1595            134.0
1596            135.0
1597            137.0
1598            138.0
1599            140.0
1600            144.0
1601            149.0


In [577]:
rq1_malaysia_df['adult mortality'] = rq1_malaysia_adultmort_df['adult mortality']

<ipython-input-577-2bf7d2ecdbeb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_malaysia_df['adult mortality'] = rq1_malaysia_adultmort_df['adult mortality']


In [578]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='adult mortality:Q',
    tooltip=['year', 'adult mortality']
).properties(
    width=600,
    height=400,
    title='Adult Mortality Over Time - Malaysia'
).interactive()

alt.Chart(...)

Inconsistencies were resolved!

#### *Number of Infant Deaths per 1000 population Over Time*

In [579]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='infant deaths:Q',
    tooltip=['year', 'infant deaths']
).properties(
    width=600,
    height=400,
    title='Infant Deaths Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Number of under-five deaths per 1000 population Over Time*

In [580]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='under-five deaths:Q',
    tooltip=['year', 'under-five deaths']
).properties(
    width=600,
    height=400,
    title='Deaths Under The Age of Five Over Time - Malaysia'
).interactive()

alt.Chart(...)

### Research Question 2 - Thailand
Thirdly, the dataframe for research question 2 for Thailand was explored.
Herefor, describe (), info() were used to find out the different means and counts of the dataframe. isnull() was used to find out if there are missing values.
Next, the variables were plotted to check for outliers, typos and other inconsistencies. These results were discussed in the next section, and in case there was missing data, it was identified, reported and resolved.

In [581]:
rq2_thailand_df.describe()

year    population          gdp  percentage expenditure  \
count    16.000000  1.600000e+01    16.000000               16.000000   
mean   2007.500000  3.117051e+07  3494.781702              401.259963   
std       4.760952  3.198737e+07  2087.128227              295.771637   
min    2000.000000  6.522310e+05    27.564826                0.000000   
25%    2003.750000  4.893510e+06  2242.488562              149.968163   
50%    2007.500000  6.734470e+06  3670.608663              377.558196   
75%    2011.250000  6.591703e+07  5572.085769              644.574649   
max    2015.000000  6.841677e+07  6171.262444              801.050465   

       under-five deaths  infant deaths  schooling  
count          16.000000      16.000000  16.000000  
mean           14.125000      12.125000  12.550000  
std             3.792537       3.180671   0.925203  
min             9.000000       8.000000  10.900000  
25%            11.000000       9.750000  11.875000  
50%            13.500000      11.500000  12.650000  
75%            16.500000      14.250000  13.375000  
max            21.000000      18.000000  13.700000

In [582]:
rq2_thailand_df.isnull().sum()

country                   0
year                      0
population                0
gdp                       0
percentage expenditure    0
under-five deaths         0
infant deaths             0
schooling                 0
dtype: int64

#### *RQ 2 - Thailand: Population Over Time*

In [583]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time - Thailand'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#9)

Here outliers were found at year 2000, 2002, 2004, 2005, 2008, 2010, 2011, 2013, and 2015. Since the same issue occured in the dataframe for research question 1, the same approach could be applied to solved it.
However, first, a table was made to ensure resemblance.

In [584]:
tablepopulation_thailandrq2 = rq2_thailand_df.groupby('year')['population'].sum().reset_index()
print(tablepopulation_thailandrq2)

    year  population
0   2000   6295821.0
1   2001  63543322.0
2   2002   6473164.0
3   2003  64554952.0
4   2004    652231.0
5   2005   6542547.0
6   2006  65824164.0
7   2007  66195615.0
8   2008   6654576.0
9   2009  66881867.0
10  2010    672888.0
11  2011    675313.0
12  2012  67843979.0
13  2013   6814365.0
14  2014  68416772.0
15  2015    686576.0


It indeed seems to be the same issue as seen with research question 1 - Thailand - population. Therefor, again a loop was made, with a threshold for 62000000. All values under that treshold will have their decimal moved to the right, until these reach over the treshold.

In [585]:
rq2_thailand_pop_df = rq2_thailand_df[['population']].copy()
population_threshold = 62000000

while rq2_thailand_pop_df['population'].min() < population_threshold:

   outliers_population = rq2_thailand_pop_df['population'] < population_threshold

   rq2_thailand_pop_df.loc[outliers_population, 'population'] *= 10

print(rq2_thailand_pop_df)

      population
2569  68657600.0
2570  68416772.0
2571  68143650.0
2572  67843979.0
2573  67531300.0
2574  67288800.0
2575  66881867.0
2576  66545760.0
2577  66195615.0
2578  65824164.0
2579  65425470.0
2580  65223100.0
2581  64554952.0
2582  64731640.0
2583  63543322.0
2584  62958210.0


This approach worked again. The incorrect values were replaced by the corrected values in the dataframe.

In [586]:
rq2_thailand_df['population'] = rq2_thailand_pop_df['population']

<ipython-input-586-66cfd1bb63ad>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_thailand_df['population'] = rq2_thailand_pop_df['population']


In [587]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Thailand) '
).interactive()

alt.Chart(...)

The inconsistencies were resolved!

#### *Gross Domestic Product per capita (in USD) Over Time*

In [588]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time - Thailand'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#10)

In [589]:
tablegdp_thailandrq2 = rq2_thailand_df.groupby('year')['gdp'].sum().reset_index()
print(tablegdp_thailandrq2)

    year          gdp
0   2000    27.564826
1   2001  1893.145377
2   2002   296.546170
3   2003  2358.936290
4   2004  2659.839180
5   2005  2893.651356
6   2006  3368.952576
7   2007  3972.264750
8   2008  4378.687460
9   2009  4212.549200
10  2010   575.321760
11  2011  5491.159981
12  2012  5859.915622
13  2013  6171.262444
14  2014  5941.847100
15  2015  5814.863134


Since this is the same as RQ 1- Thailand - GDP, the same approach was used here.

A table was made to visualise the outliers better.

In [590]:
#seperate gdp df was made with only population
rq2_thailand_gdp_df = rq2_thailand_df[['gdp']].copy()

In [591]:
#threshold was set at 1893
gdp_threshold = 1893

#loop to identify outliers

while rq2_thailand_gdp_df['gdp'].min() < gdp_threshold:

   outliers_gdp = rq2_thailand_gdp_df['gdp'] < gdp_threshold

#drop rows corresponding to outliers
   rq2_thailand_gdp_df = rq2_thailand_gdp_df[~outliers_gdp]

print(rq2_thailand_gdp_df)

              gdp
2569  5814.863134
2570  5941.847100
2571  6171.262444
2572  5859.915622
2573  5491.159981
2575  4212.549200
2576  4378.687460
2577  3972.264750
2578  3368.952576
2579  2893.651356
2580  2659.839180
2581  2358.936290
2583  1893.145377


In [592]:
rq2_thailand_df['gdp'] = rq2_thailand_gdp_df['gdp']

<ipython-input-592-63ac10d20f02>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_thailand_df['gdp'] = rq2_thailand_gdp_df['gdp']


In [593]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Thailand) '
).interactive()

alt.Chart(...)

In [594]:
rq2_thailand_gdp2_df = rq2_thailand_df[['gdp']].copy()

In [595]:
#the 0s were replaced with nans
rq2_thailand_gdp2_df.replace(0, np.nan, inplace=True)

#missing values in the df were interpolated
rq2_thailand_gdp2_df['gdp'] = rq2_thailand_gdp2_df['gdp'].interpolate(method='linear')


print(rq2_thailand_gdp2_df)

              gdp
2569  5814.863134
2570  5941.847100
2571  6171.262444
2572  5859.915622
2573  5491.159981
2574  4851.854591
2575  4212.549200
2576  4378.687460
2577  3972.264750
2578  3368.952576
2579  2893.651356
2580  2659.839180
2581  2358.936290
2582  2126.040834
2583  1893.145377
2584  1893.145377


In [596]:
rq2_thailand_df['gdp'] = rq2_thailand_gdp2_df['gdp']

<ipython-input-596-5e915c98e795>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_thailand_df['gdp'] = rq2_thailand_gdp2_df['gdp']


In [597]:
alt.Chart(rq1_thailand_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Thailand) '
).interactive()

alt.Chart(...)

#### *Expenditure on health as a percentage of Gross Domestic Product per capita(%) Over Time*

In [598]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage Expenditure Over Time - Thailand'
).interactive()

alt.Chart(...)

#### Identification and Reporting and Resolving of missing data and inconsistencies (#11)

Here, the same problem seems to have occured as in RQ1 Thailand Percentage expenditure. A table was made to visualise and confirm.

In [599]:
tableexp_thailandrq2 = rq2_thailand_df.groupby('year')['percentage expenditure'].sum().reset_index()
print(tableexp_thailandrq2)

    year  percentage expenditure
0   2000                0.275648
1   2001              176.062520
2   2002               27.638103
3   2003              282.836461
4   2004              301.359779
5   2005              321.195300
6   2006              433.921092
7   2007              520.763909
8   2008              609.951163
9   2009              547.210141
10  2010               71.685091
11  2011              748.445105
12  2012              801.050465
13  2013              788.687340
14  2014              789.077295
15  2015                0.000000


Here too, the decimal seems to be placed wrongly. The same approach as for RQ1 Thailand Percentage Expenditure was executed.

In [600]:
#seperate exp df was made with only expenditure percentage
rq2_thailand_exp_df = rq2_thailand_df[['percentage expenditure']].copy()

In [601]:
exp_threshold = 100

while rq2_thailand_exp_df['percentage expenditure'].max() > exp_threshold:

   outliers_exp = rq2_thailand_exp_df['percentage expenditure'] > exp_threshold

   rq2_thailand_exp_df.loc[outliers_exp, 'percentage expenditure'] /= 10

print(rq2_thailand_exp_df)

      percentage expenditure
2569                0.000000
2570               78.907729
2571               78.868734
2572               80.105047
2573               74.844511
2574               71.685091
2575               54.721014
2576               60.995116
2577               52.076391
2578               43.392109
2579               32.119530
2580               30.135978
2581               28.283646
2582               27.638103
2583               17.606252
2584                0.275648


In [602]:
from sklearn.linear_model import LinearRegression

#year values extracted
years = rq2_thailand_exp_df.index.values.reshape(-1, 1)

#percentage expenditure values extracted
expenditure = rq2_thailand_exp_df['percentage expenditure'].values.reshape(-1, 1)

#linear regression model fitted
model = LinearRegression()
model.fit(years, expenditure)

#the first and last values extrapolated using the linear model
first_value = model.predict([[years[0][0] - 1]])[0][0]
last_value = model.predict([[years[-1][0] + 1]])[0][0]

#the first and last values updated in the df
rq2_thailand_exp_df.iloc[0, 0] = first_value
rq2_thailand_exp_df.iloc[-1, 0] = last_value

print(rq2_thailand_exp_df)


      percentage expenditure
2569               75.433519
2570               78.907729
2571               78.868734
2572               80.105047
2573               74.844511
2574               71.685091
2575               54.721014
2576               60.995116
2577               52.076391
2578               43.392109
2579               32.119530
2580               30.135978
2581               28.283646
2582               27.638103
2583               17.606252
2584               16.023344


In [603]:
rq2_thailand_df['percentage expenditure'] = rq2_thailand_exp_df['percentage expenditure']

<ipython-input-603-ba1ae15abb66>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_thailand_df['percentage expenditure'] = rq2_thailand_exp_df['percentage expenditure']


In [604]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage expenditure Over Time (Thailand) '
).interactive()

alt.Chart(...)

#### *Number of under-five deaths per 1000 population Over Time*

In [605]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='under-five deaths:Q',
    tooltip=['year', 'under-five deaths']
).properties(
    width=600,
    height=400,
    title='Under-Five Deaths Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Number of Infant Deaths per 1000 population Over Time*

In [606]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='infant deaths:Q',
    tooltip=['year', 'infant deaths']
).properties(
    width=600,
    height=400,
    title='Infant Deaths Over Time - Thailand'
).interactive()

alt.Chart(...)

#### *Number Of Years Of Schooling Over Time*

In [607]:
alt.Chart(rq2_thailand_df).mark_line().encode(
    x='year:O',
    y='schooling:Q',
    tooltip=['year', 'schooling']
).properties(
    width=600,
    height=400,
    title='Number of Years of Schooling Over Time - Thailand'
).interactive()

alt.Chart(...)

### Research Question 2 - Malaysia
Thirdly, the dataframe for research question 2 for Malaysia was explored.
Herefor, describe (), info() were used to find out the different means and counts of the dataframe. isnull() was used to find out if there are missing values.
Next, the variables were plotted to check for outliers, typos and other inconsistencies. These results were discussed in the next section, and in case there was missing data, it was identified, reported and resolved.

In [608]:
rq2_malaysia_df.describe()

year    population           gdp  percentage expenditure  \
count    16.000000  1.600000e+01     16.000000               16.000000   
mean   2007.500000  1.152916e+07   4904.938992              248.885028   
std       4.760952  1.208221e+07   3338.811459              197.722652   
min    2000.000000  3.228170e+05    145.126200                0.000000   
25%    2003.750000  2.505282e+06   1856.582918               92.598583   
50%    2007.500000  2.947090e+06   4709.576818              240.476280   
75%    2011.250000  2.578044e+07   7283.564464              376.928861   
max    2015.000000  2.863513e+07  11183.961910              721.365543   

       under-five deaths  infant deaths  schooling  
count          16.000000      16.000000  16.000000  
mean            4.125000       3.312500  12.562500  
std             0.341565       0.478714   0.452953  
min             4.000000       3.000000  11.600000  
25%             4.000000       3.000000  12.250000  
50%             4.000000       3.000000  12.700000  
75%             4.000000       4.000000  12.900000  
max             5.000000       4.000000  13.100000

In [609]:
rq2_malaysia_df.isnull().sum()

country                   0
year                      0
population                0
gdp                       0
percentage expenditure    0
under-five deaths         0
infant deaths             0
schooling                 0
dtype: int64

#### *RQ 2 - Malaysia: Population Over Time*

In [610]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#12)

Here, outliers were spotted at year 200, 2001, 2003, 2004, 2008, 2009, 2012, 2013, 2014, and 2015.
To visualise the data, a table was made.

In [611]:
tablepopulation_malaysiarq2 = rq2_malaysia_df.groupby('year')['population'].sum().reset_index()
print(tablepopulation_malaysiarq2)

    year  population
0   2000   2318568.0
1   2001   2369897.0
2   2002  24198811.0
3   2003   2468873.0
4   2004   2517419.0
5   2005  25659393.0
6   2006  26143566.0
7   2007  26625845.0
8   2008   2711169.0
9   2009   2765383.0
10  2010  28112289.0
11  2011  28635128.0
12  2012   2917456.0
13  2013   2976724.0
14  2014    322817.0
15  2015   3723155.0


Again, like with the other population values, the issue seems to be missplaced decimals. Therefor, the same approach was applied. The population in Malaysia was 22000000 in the year 2000. Thus, this was set as a threshold for the loop. All values under 22 million had their decimal moved one place to the right.

In [612]:
rq2_malaysia_pop_df = rq2_malaysia_df[['population']].copy()
population_threshold = 22000000

while rq2_malaysia_pop_df['population'].min() < population_threshold:

   outliers_population = rq2_malaysia_pop_df['population'] < population_threshold

   rq2_malaysia_pop_df.loc[outliers_population, 'population'] *= 10

print(rq2_malaysia_pop_df)

      population
1586  37231550.0
1587  32281700.0
1588  29767240.0
1589  29174560.0
1590  28635128.0
1591  28112289.0
1592  27653830.0
1593  27111690.0
1594  26625845.0
1595  26143566.0
1596  25659393.0
1597  25174190.0
1598  24688730.0
1599  24198811.0
1600  23698970.0
1601  23185680.0


The approach worked. The incorrect values were replaced by the corrected values in the RQ2-Malaysia dataframe. To check, the population was plotted over time again.

In [613]:
rq2_malaysia_df['population'] = rq2_malaysia_pop_df['population']

<ipython-input-613-04c605b2bcda>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_malaysia_df['population'] = rq2_malaysia_pop_df['population']


In [614]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    tooltip=['year', 'population']
).properties(
    width=600,
    height=400,
    title='Population Over Time (Malaysia) '
).interactive()

alt.Chart(...)

The inconsistencies were resolved!

#### *Gross Domestic Product per capita (in USD) Over Time*

In [615]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#13)

Here, the issue is the same as for RQ 1 - Malaysia GDP. Therefor, the same approach was applied.

In [616]:
tablegdp_malaysiarq2 = rq2_malaysia_df.groupby('year')['gdp'].sum().reset_index()
print(tablegdp_malaysiarq2)

    year           gdp
0   2000    445.174710
1   2001   3915.115460
2   2002   4167.364387
3   2003   4463.675893
4   2004   4955.477743
5   2005   5593.822995
6   2006   6222.982955
7   2007   7269.171140
8   2008   8513.629541
9   2009   7326.744435
10  2010    971.356987
11  2011    145.126200
12  2012   1779.496410
13  2013   1882.278420
14  2014  11183.961910
15  2015   9643.644683


In [617]:
rq1_malaysia_gdp_df = rq1_malaysia_df[['gdp']].copy()

In [618]:
#threshold
gdp_threshold = 3915

#loop
while rq1_malaysia_gdp_df['gdp'].min() < gdp_threshold:

   outliers_gdp = rq1_malaysia_gdp_df['gdp'] < gdp_threshold

   rq1_malaysia_gdp_df.loc[outliers_gdp, 'gdp'] *= 10

print(rq1_malaysia_gdp_df)

               gdp
1586   9643.644683
1587  11183.961910
1588  18822.784200
1589  17794.964100
1590  14512.620000
1591   9713.569870
1592   7326.744435
1593   8513.629541
1594   7269.171140
1595   6222.982955
1596   5593.822995
1597   4955.477743
1598   4463.675893
1599   4167.364387
1600   3915.115460
1601   4451.747100


In [619]:
#merge with original df
rq1_malaysia_df['gdp'] = rq1_malaysia_gdp_df['gdp']

<ipython-input-619-a010c89eaa23>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq1_malaysia_df['gdp'] = rq1_malaysia_gdp_df['gdp']


In [620]:
alt.Chart(rq1_malaysia_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    tooltip=['year', 'gdp']
).properties(
    width=600,
    height=400,
    title='GDP Over Time (Malaysia) '
).interactive()

alt.Chart(...)

Inconsistencies were resolved!

#### *Expenditure on health as a percentage of Gross Domestic Product per capita(%) Over Time*

In [621]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage Expenditure Over Time - Malaysia'
).interactive()

alt.Chart(...)

##### Identification and Reporting and Resolving of missing data and inconsistencies (#14)

Here, there are outliers in the year 2000, 2010, 2011, 2012, 2013 and 2015. To visualise, a table was made.

In [622]:
tableexp_malaysiarq2 = rq2_malaysia_df.groupby('year')['percentage expenditure'].sum().reset_index()
print(tableexp_malaysiarq2)

    year  percentage expenditure
0   2000               23.371672
1   2001              210.241700
2   2002              216.702948
3   2003              264.249613
4   2004              315.663932
5   2005              297.591383
6   2006              365.911398
7   2007              409.981252
8   2008              438.451921
9   2009              431.545247
10  2010               65.566597
11  2011                9.230026
12  2012              101.609245
13  2013              110.677971
14  2014              721.365543
15  2015                0.000000


Here, the problem seems to be the same as with R1 - Thailand Percentage Expenditure. The same approach was applied. However, some are just a bit above 100. These probably have not a misplaced decimal. Therefor, the threshold was set at 112.

In [623]:
rq2_malaysia_exp_df = rq2_malaysia_df[['percentage expenditure']].copy()

exp_threshold = 112

while rq2_malaysia_exp_df['percentage expenditure'].max() > exp_threshold:

   outliers_exp = rq2_malaysia_exp_df['percentage expenditure'] > exp_threshold

   rq2_malaysia_exp_df.loc[outliers_exp, 'percentage expenditure'] /= 10

print(rq2_malaysia_exp_df)

      percentage expenditure
1586                0.000000
1587               72.136554
1588              110.677971
1589              101.609245
1590                9.230026
1591               65.566597
1592               43.154525
1593               43.845192
1594               40.998125
1595               36.591140
1596               29.759138
1597               31.566393
1598               26.424961
1599               21.670295
1600               21.024170
1601               23.371672


In [624]:

#exp_threshold2 = 10

#while rq2_malaysia_exp_df['percentage expenditure'].min() < exp_threshold2:

#   outliers_exp2 = rq2_malaysia_exp_df['percentage expenditure'] < exp_threshold2

#   rq2_malaysia_exp_df.loc[outliers_exp2, 'percentage expenditure'] *= 10

#print(rq2_malaysia_exp_df)

The cell above does not seem to be working. It keeps loading for minutes on end. This step was needed to change the 9 to 90%. We decided to keep this out of the code.

In [625]:
from sklearn.linear_model import LinearRegression

#the year values extracted
years = rq2_malaysia_exp_df.index.values.reshape(-1, 1)

#the percentage expenditure values extracted
expenditure = rq2_malaysia_exp_df['percentage expenditure'].values.reshape(-1, 1)

#the linear regression model fitted
model = LinearRegression()
model.fit(years[1:], expenditure[1:])

# the first value using the linear model extrapolated
first_value = model.predict([[years[0][0] - 1]])[0][0]

# first value in the df updated
rq2_malaysia_exp_df.iloc[0, 0] = first_value

print(rq2_malaysia_exp_df)

      percentage expenditure
1586               88.446984
1587               72.136554
1588              110.677971
1589              101.609245
1590                9.230026
1591               65.566597
1592               43.154525
1593               43.845192
1594               40.998125
1595               36.591140
1596               29.759138
1597               31.566393
1598               26.424961
1599               21.670295
1600               21.024170
1601               23.371672


In [626]:
rq2_malaysia_df['percentage expenditure'] = rq2_malaysia_exp_df['percentage expenditure']

<ipython-input-626-5ed0983b0cbc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rq2_malaysia_df['percentage expenditure'] = rq2_malaysia_exp_df['percentage expenditure']


In [627]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    tooltip=['year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title='Percentage expenditure Over Time (Malaysia) '
).interactive()

alt.Chart(...)

#### *Number of under-five deaths per 1000 population Over Time*

In [628]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='under-five deaths:Q',
    tooltip=['year', 'under-five deaths']
).properties(
    width=600,
    height=400,
    title='Under-Five Deaths Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Number of Infant Deaths per 1000 population Over Time*

In [629]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='infant deaths:Q',
    tooltip=['year', 'infant deaths']
).properties(
    width=600,
    height=400,
    title='Infant Deaths Over Time - Malaysia'
).interactive()

alt.Chart(...)

#### *Number of years of Schooling Over Time*

In [630]:
alt.Chart(rq2_malaysia_df).mark_line().encode(
    x='year:O',
    y='schooling:Q',
    tooltip=['year', 'schooling']
).properties(
    width=600,
    height=400,
    title='Number Of Years Of Schooling Over Time - Malaysia'
).interactive()

alt.Chart(...)

# **Data Description and Visualisation**

Provide a description of the population for the reader (e.g. countries or continents) relevant to your question using a table with descriptive statistics (i.e. means, medians, standard deviations) and where possible visualisation. ***(15pt)***
Make the report interactive: Create at least one interactive visualisation using input from the user. ***(20pt)***
Turn your interactive report into an application using GitHub, Voila and Binder.***(15pt)***

## Research Question 1
How does the allocation of healthcare expenditure and vaccination coverage differ between Thailand and Malaysia, and what impact do these differences have on health outcomes such as life expectancy and infant mortality?

In the tables below, the means, standard deviations and medians can be appreciated.

---



In [631]:
rq1_thailand_df.describe()

year    population          gdp  percentage expenditure  \
count    16.000000  1.600000e+01    16.000000               16.000000   
mean   2007.500000  6.623539e+07  3993.007204               51.427257   
std       4.760952  1.733619e+06  1567.943296               23.605095   
min    2000.000000  6.295821e+07  1893.145377               16.023344   
25%    2003.750000  6.510024e+07  2584.613458               29.672895   
50%    2007.500000  6.637069e+07  4092.406975               53.398702   
75%    2011.250000  6.760947e+07  5572.085769               74.991763   
max    2015.000000  6.865760e+07  6171.262444               80.105047   

       hepatitis b    polio  diphtheria  life expectancy  adult mortality  \
count    16.000000  16.0000   16.000000        16.000000        16.000000   
mean     97.000000  98.3125   98.187500        73.081250       169.375000   
std       1.505545   0.7932    1.046821         1.320716        16.962213   
min      95.000000  97.0000   96.000000        71.100000       148.000000   
25%      96.000000  98.0000   98.000000        71.675000       154.750000   
50%      97.000000  98.5000   98.500000        73.400000       163.500000   
75%      98.000000  99.0000   99.000000        74.150000       189.000000   
max      99.000000  99.0000   99.000000        74.900000       194.000000   

       infant deaths  under-five deaths  
count      16.000000          16.000000  
mean       12.125000          14.125000  
std         3.180671           3.792537  
min         8.000000           9.000000  
25%         9.750000          11.000000  
50%        11.500000          13.500000  
75%        14.250000          16.500000  
max        18.000000          21.000000

In [632]:
rq1_malaysia_df.describe()

year    population           gdp  percentage expenditure  \
count    16.000000  1.600000e+01     16.000000               16.000000   
mean   2007.500000  2.745895e+07   8659.454776               47.879562   
std       4.760952  3.564517e+06   4762.663602               30.711759   
min    2000.000000  2.318568e+07   3915.115460                9.230026   
25%    2003.750000  2.505282e+07   4832.527281               25.661639   
50%    2007.500000  2.686877e+07   7297.957787               38.794633   
75%    2011.250000  2.876999e+07  10081.167880               67.209086   
max    2015.000000  3.723155e+07  18822.784200              110.677971   

       hepatitis b      polio  diphtheria  life expectancy  adult mortality  \
count    16.000000  16.000000   16.000000        16.000000        16.000000   
mean     96.000000  96.375000   96.437500        73.756250       133.750000   
std       1.154701   1.258306    1.209339         0.772846         6.688298   
min      94.000000  94.000000   94.000000        72.400000       123.000000   
25%      95.000000  95.750000   96.000000        73.175000       129.750000   
50%      96.000000  96.500000   96.500000        73.750000       132.500000   
75%      96.250000  97.000000   97.000000        74.350000       137.250000   
max      99.000000  99.000000   99.000000        75.000000       149.000000   

       infant deaths  under-five deaths  
count      16.000000          16.000000  
mean        3.312500           4.125000  
std         0.478714           0.341565  
min         3.000000           4.000000  
25%         3.000000           4.000000  
50%         3.000000           4.000000  
75%         4.000000           4.000000  
max         4.000000           5.000000

In order to compare the two countries, the dataframes from Thailand and Malaysia were concatenated.

In [633]:
rq1_concat_df = pd.concat([rq1_thailand_df, rq1_malaysia_df], ignore_index=True)


Over the years, both countries grew in population. Thailand has a bigger population, however Malaysia grew the most, especially in the early 2010s.

In [634]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='population:Q',
    color='country:N',
    tooltip=['country', 'year', 'population']
).properties(
    width=600,
    height=400,
    title="Population Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

Both countries grew in GDP per capita over the years, and alongside, their percentage spent on health care grew.



In [635]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='gdp:Q',
    color='country:N',
    tooltip=['country', 'year', 'gdp']
).properties(
    width=600,
    height=400,
    title="GDP Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

In [636]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='percentage expenditure:Q',
    color='country:N',
    tooltip=['country', 'year', 'percentage expenditure']
).properties(
    width=600,
    height=400,
    title="Percentage expenditure Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

Surprisingly though, the immunization coverage for Hepatitis B, Polio and Diphtheria of 1 year old in percentage, was already high in the 90% in 2000 for both countries, and stayed high.

In [637]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='hepatitis b:Q',
    color='country:N',
    tooltip=['country', 'year', 'hepatitis b']
).properties(
    width=600,
    height=400,
    title="Hepatitis B Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

In [638]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='polio:Q',
    color='country:N',
    tooltip=['country', 'year', 'polio']
).properties(
    width=600,
    height=400,
    title="Polio Vaccination Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

In [639]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='diphtheria:Q',
    color='country:N',
    tooltip=['country', 'year', 'diphtheria']
).properties(
    width=600,
    height=400,
    title="Diphtheria Vaccination Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

When looking at other health variables, like life expectancy, there was a similar growth in both countries, from the low 70s in 2000 to middle 70s in 2015.


In [640]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='life expectancy:Q',
    color='country:N',
    tooltip=['country', 'year', 'life expectancy']
).properties(
    width=600,
    height=400,
    title="Life Expectancy Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

Adult mortality has a similar downward trend in both countries as well. The difference between the countries lies in that Thailand's adult mortality was higher and still is higher than Malaysia.

In [641]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='adult mortality:Q',
    color='country:N',
    tooltip=['country', 'year', 'adult mortality']
).properties(
    width=600,
    height=400,
    title="Adult Mortality Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

One of the biggest differences is seen in infant deaths. In Malaysia, the infant death rate has been stable around 3 or 4 per 1000. In Thailand however, there were 18 deaths per 1000. This number decreased until 8 in 2015.

In [642]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='infant deaths:Q',
    color='country:N',
    tooltip=['country', 'year', 'infant deaths']
).properties(
    width=600,
    height=400,
    title="Infant deaths Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

In under-five deaths, the other big difference is seen. Here, Malaysia lies stable throughout the years with 4-5 deaths under 5 year old per 1000. In Thailand however, this number is larger again, although there is a steady decreasing trend. In 2000, the country had 21 under-five deaths per 1000, while in 2015 it dropped to 9 under-five deaths per 1000.

In [643]:
alt.Chart(rq1_concat_df).mark_line().encode(
    x='year:O',
    y='under-five deaths:Q',
    color='country:N',
    tooltip=['country', 'year', 'under-five deaths']
).properties(
    width=600,
    height=400,
    title="Under-five deaths Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

## Research Question 2
Research Question 2: To what extent does the level of education, as measured by schooling years, correlate with health outcomes such as life expectancy and infant mortality in Thailand and Malaysia, and how does this relationship compare between the two countries?

In the tables below, the means, standard deviations and medians can be appreciated.

In [644]:
rq2_thailand_df.describe()

year    population          gdp  percentage expenditure  \
count    16.000000  1.600000e+01    16.000000               16.000000   
mean   2007.500000  6.623539e+07  3993.007204               51.427257   
std       4.760952  1.733619e+06  1567.943296               23.605095   
min    2000.000000  6.295821e+07  1893.145377               16.023344   
25%    2003.750000  6.510024e+07  2584.613458               29.672895   
50%    2007.500000  6.637069e+07  4092.406975               53.398702   
75%    2011.250000  6.760947e+07  5572.085769               74.991763   
max    2015.000000  6.865760e+07  6171.262444               80.105047   

       under-five deaths  infant deaths  schooling  
count          16.000000      16.000000  16.000000  
mean           14.125000      12.125000  12.550000  
std             3.792537       3.180671   0.925203  
min             9.000000       8.000000  10.900000  
25%            11.000000       9.750000  11.875000  
50%            13.500000      11.500000  12.650000  
75%            16.500000      14.250000  13.375000  
max            21.000000      18.000000  13.700000

In [645]:
rq2_malaysia_df.describe()

year    population           gdp  percentage expenditure  \
count    16.000000  1.600000e+01     16.000000               16.000000   
mean   2007.500000  2.745895e+07   4904.938992               47.879562   
std       4.760952  3.564517e+06   3338.811459               30.711759   
min    2000.000000  2.318568e+07    145.126200                9.230026   
25%    2003.750000  2.505282e+07   1856.582918               25.661639   
50%    2007.500000  2.686877e+07   4709.576818               38.794633   
75%    2011.250000  2.876999e+07   7283.564464               67.209086   
max    2015.000000  3.723155e+07  11183.961910              110.677971   

       under-five deaths  infant deaths  schooling  
count          16.000000      16.000000  16.000000  
mean            4.125000       3.312500  12.562500  
std             0.341565       0.478714   0.452953  
min             4.000000       3.000000  11.600000  
25%             4.000000       3.000000  12.250000  
50%             4.000000       3.000000  12.700000  
75%             4.000000       4.000000  12.900000  
max             5.000000       4.000000  13.100000

In order to better visualise the similarities and differences between the countries for this research question, the two dataframes were concatenated.

In [646]:
rq2_concat_df = pd.concat([rq2_thailand_df, rq2_malaysia_df], ignore_index=True)

For this reseach question, the variables population, GDP, percentage expenditure, under-five deaths, infant deaths and schooling were compared for the two countries. Since the first 5 variables resemble the variables in reseach question 1, here schooling is compared between the two countries.

The countries are very similar for this variable. In both countries, children had approximately 11 schooling years, and grew to have approximately 13 schooling years in 2015.

In [647]:
alt.Chart(rq2_concat_df).mark_line().encode(
    x='year:O',
    y='schooling:Q',
    color='country:N',
    tooltip=['country', 'year', 'schooling']
).properties(
    width=600,
    height=400,
    title="Schooling Over Time - Thailand and Malaysia"
).interactive()

alt.Chart(...)

# **Conclusion**

Summarise the work and the main findings related to the initial research question. ***(5 pt)***

## *Summary and Main Findings*
### Research Question 1
Both Thailand and Malaysia experienced growth in population, GDP, and percentage expenditure on health over the period from 2000 to 2015. The vaccination rates for polio, hepatitis B, and diphtheria were already high in 2000 and remained consistently high throughout the years for both countries. In regards to the health variables as life expectancy and adult mortality, both countries showed a small downward trend over the years. However, health variables such as infant deaths and under-five deaths stayed low and stable in Malaysia. In Thailand, these variables were higher in the 2000s and had a decreasing line. Since Thailand has high vaccination rates for hepatitis b, polio and diphtheria, this suggests other factors influencing these outcomes. Further research is needed to understand the reasons behind the decrease in infant deaths and under-five deaths in Thailand.
### Research Question 2
In conclusion, both Thailand and Malaysia exhibited growth in population, GDP, and percentage expenditure on health from 2000 to 2015. While Malaysia maintained low and stable levels of infant deaths, Thailand saw a steady decrease, albeit not reaching Malaysia's levels. A similar trend was observed for deaths under the age of five. Interestingly, there was only a slight increase in schooling years over the same period. However, no clear correlation was found between health factors for children and schooling years. Further research is warranted to explore the underlying reasons behind these trends.

# **STATEMENT OF EQUAL CONTRIBURTION**

For this assignment, we, Ilse Heijnen and Paula Dewenter, worked together to tackle different parts of the task.

Ilse Heijnen focused on Research Question 1, examining the relationship between healthcare expenditure and vaccination coverage in developing countries.

Paula Dewenter took on Research Question 2, exploring the link between GDP, healthcare expenditure, health outcomes and education.

As Research Question 1 showed to require more time than Research Question 2, we collaborated on this one to ensure equal participation.

Overall, our collaboration allowed us to successfully address the research questions and complete the assignment.